apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx # Specifies that this Ingress resource should be handled by the nginx Ingress controller.
  name: murphy-movies-ingress # Names this Ingress resource as "murphy-movies-ingress".
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: murphy-movies-login-service # Points to the service named "murphy-movies-service". The value should match the name of the service.
                port:
                  number: 8080 # Specifies that the service is listening on port 8080.
            path: / # # Defines the path to match incoming requests. Here, "/" means the root path.
            pathType: Prefix # # Indicates that the path is a prefix match, so any request path starting with "/" will be routed to the backend service.
          - backend:
              service:
                name: murphy-movies-star-service # Points to the service named "murphy-movies-service". The value should match the name of the service.
                port:
                  number: 8080 # Specifies that the service is listening on port 8080.
            path: /api/single-star, /api/comments # # Defines the path to match incoming requests. Here, "/" means the root path.
            pathType: Prefix # # Indicates that the path is a prefix match, so any request path starting with "/" will be routed to the backend service.